# Assignment

# 1.version

In [1]:
# To check the version of numpy package
import numpy as np
# To check the version of numpy package
import numpy as np
np.__version__

'1.16.2'

## 2. Create a 1D array of numbers from 0 to 10

In [2]:
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a 3×3 numpy array of all True’s(1's)

In [3]:
array_ones = np.ones((3,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 4. Convert a 1D array to a 2D array with 2 rows

In [4]:
array_1d.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 5. Write a NumPy program to generate six random integers between 10 and 30

In [5]:
import random
array_random = np.random.randint(10,31,6)
array_random

array([25, 27, 14, 18, 18, 27])

## 6. Write a NumPy program to create a 3x3x3 array with random values

In [6]:
array_randomat = np.random.rand(3,3,3)
array_randomat

array([[[0.06503172, 0.76272853, 0.66379477],
        [0.03510948, 0.26806832, 0.84710867],
        [0.17756814, 0.17504138, 0.27116359]],

       [[0.27630259, 0.06028679, 0.47122971],
        [0.05666534, 0.37331699, 0.62062351],
        [0.40533207, 0.39921431, 0.19028628]],

       [[0.58185313, 0.90311474, 0.42442517],
        [0.40593244, 0.13630264, 0.16509527],
        [0.69693587, 0.20713239, 0.87164856]]])

## 7.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [7]:
array_rand55 = np.random.rand(5,5)
print(array_rand55)
print(np.amin(array_rand55))
print(np.amax(array_rand55))

[[0.90472429 0.59122472 0.17421143 0.01852445 0.41493024]
 [0.15902933 0.26757046 0.22714638 0.40528093 0.85567218]
 [0.10882307 0.5203442  0.23436278 0.85863162 0.14892696]
 [0.75040417 0.79499392 0.57433882 0.64829938 0.57064567]
 [0.73649569 0.19834991 0.40473952 0.62114063 0.82536181]]
0.018524452143121484
0.9047242900278283


## 8 Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [8]:
array_rand104 = np.random.rand(10,4)
array_rand104

array([[0.72228229, 0.21761549, 0.63738714, 0.39901488],
       [0.39697907, 0.19294948, 0.14684385, 0.71564549],
       [0.24164095, 0.32816488, 0.76266373, 0.2907497 ],
       [0.41729177, 0.7964698 , 0.05858426, 0.86805776],
       [0.87205116, 0.56855272, 0.60670859, 0.48796579],
       [0.0563559 , 0.99976523, 0.12766662, 0.91354458],
       [0.07611311, 0.20528414, 0.96366153, 0.7074151 ],
       [0.64346393, 0.05642425, 0.60114871, 0.42917304],
       [0.02624391, 0.56035946, 0.80352701, 0.60856247],
       [0.3336459 , 0.43188033, 0.02049183, 0.12548327]])

In [9]:
array_rand104[:5]

array([[0.72228229, 0.21761549, 0.63738714, 0.39901488],
       [0.39697907, 0.19294948, 0.14684385, 0.71564549],
       [0.24164095, 0.32816488, 0.76266373, 0.2907497 ],
       [0.41729177, 0.7964698 , 0.05858426, 0.86805776],
       [0.87205116, 0.56855272, 0.60670859, 0.48796579]])

## 9.How to reverse the rows of a 2D array?
arr = np.arange(9).reshape(3,3)
a = [[1,2,3],[2,3,4],[3,4,5]]

out = [[3,4,5],[2,3,4],[1,2,3]]

In [10]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [12]:
a = [[1,2,3],[2,3,4],[3,4,5]]
a[::-1]

[[3, 4, 5], [2, 3, 4], [1, 2, 3]]

## 10. Create 1D array with random numbers and replace all odd numbers in arr with -1

In [14]:
import numpy as np
array_final = np.random.randint(1,100,10)
array_final

array([25, 89, 16, 62, 93, 57, 11,  6, 67, 75])

In [15]:
for i in range(len(array_final)):
    if array_final[i]%2==1:
        array_final[i] = -1
array_final

array([-1, -1, 16, 62, -1, -1, -1,  6, -1, -1])